services:
  supabase-db:
    image: postgres:15
    container_name: supabase-db
    ports:
      - '54322:5432'
    environment:
      POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
      POSTGRES_DB: postgres
    volumes:
      - supabase_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  supabase-rest:
    image: postgrest/postgrest:v11.2.0
    container_name: supabase-rest
    ports:
      - '54321:3000'
    environment:
      PGRST_DB_URI: postgres://postgres:your-super-secret-and-long-postgres-password@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_DB_USE_LEGACY_GUCS: false
    depends_on:
      - supabase-db

volumes:
  supabase_db_data:
  supabase_storage_data:
